# Introduction to SQL

SQL (Structured Query Language) is a standard programming language used to manage and manipulate relational databases.

It is used to:
- Create and modify database structures
- Insert, update, and delete data
- Retrieve data using queries
- Maintain data integrity using constraints

In cybersecurity systems, SQL is used to store:
- Incident logs
- Vulnerability records
- Attack classifications
- Risk scores

In this notebook, we demonstrate:
- CREATE TABLE
- PRIMARY KEY
- INSERT statements
- Basic SELECT query

In [2]:
import sqlite3
import pandas as pd
# Create in-memory database
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

print("Database created successfully!")

Database created successfully!

## CREATE TABLE Statement

We create a table to store cybersecurity incident data.

In [3]:
cursor.execute("""
CREATE TABLE CyberIncidents (
    Incident_ID INTEGER PRIMARY KEY,
    Timestamp TEXT,
    Source_Country TEXT,
    Target_System TEXT,
    Attack_Type TEXT,
    Severity_Level TEXT,
    Risk_Score INTEGER
);
""")

print("Table created successfully!")

Table created successfully!

## INSERT Statement

Now we insert cybersecurity incident records into the table.

In [4]:
cursor.executemany("""
INSERT INTO CyberIncidents
(Incident_ID, Timestamp, Source_Country, Target_System, Attack_Type, Severity_Level, Risk_Score)
VALUES (?, ?, ?, ?, ?, ?, ?)
""", [
    (101, '2024-06-01 10:30:00', 'USA', 'Web Server', 'DDoS', 'High', 3),
    (102, '2024-06-02 14:20:00', 'India', 'Database', 'Phishing', 'Medium', 2),
    (103, '2024-06-03 09:15:00', 'Germany', 'Cloud VM', 'Ransomware', 'Critical', 4)
])

conn.commit()

print("Data inserted successfully!")

Data inserted successfully!

## SELECT Statement

Retrieve all records from the table.

In [5]:
df = pd.read_sql_query("SELECT * FROM CyberIncidents", conn)
df

,Incident_ID,Timestamp,Source_Country,Target_System,Attack_Type,Severity_Level,Risk_Score
0,101,2024-06-01 10:30:00,USA,Web Server,DDoS,High,3
1,102,2024-06-02 14:20:00,India,Database,Phishing,Medium,2
2,103,2024-06-03 09:15:00,Germany,Cloud VM,Ransomware,Critical,4

## Filtering Critical Incidents

Using WHERE clause to filter high severity threats.

In [6]:
critical_df = pd.read_sql_query("""
SELECT Incident_ID, Attack_Type, Severity_Level
FROM CyberIncidents
WHERE Severity_Level = 'Critical';
""", conn)

critical_df

   Incident_ID Attack_Type Severity_Level
0          103  Ransomware       Critical

In [7]:
conn.close()
print("Database connection closed.")

Database connection closed.

# Conclusion

This notebook demonstrated:

- What SQL is
- CREATE TABLE statement
- PRIMARY KEY constraint
- INSERT statement
- SELECT query with filtering

SQL is essential for storing, managing, and retrieving
cybersecurity incident data efficiently.

It forms the backend foundation of data-driven dashboards.